#!/bin/bash

git tag `echo "$CIRCLE_BRANCH-source" | sed s/release-//` &&
git config --global user.email "circleci@chlorine.plugin" &&
git config --global user.name "CircleCI Automated Build" &&
git checkout -b release-prepare-DELETE-THIS &&
git rm -r src scripts &&
git add -f lib/* &&
git commit -m 'Compiled version for release' &&
git tag `echo $CIRCLE_BRANCH | sed s/release-//` &&
git push --tags
